on:
  push:
    branches: [main] # remplacer "main" par le nom de la branche que vous souhaitez surveiller

jobs:
  check-code-conformity:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install PHP and Composer
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4' # Remplacer "7.4" par la version de PHP que vous utilisez
        coverage: none
    - name: Install PHP Code Sniffer
      run: composer global require "squizlabs/php_codesniffer=*"
    - name: Check code conformity
      run: phpcs --standard=PSR2 code.php
